name: ChestRegeneration
main: me.FluffyWolfers.CR.CR
version: 1.0
commands:
  chestregen:
    description: Main command for ChestRegeneration plugin
    permission: chestregen.cr
    permission-message: No no no!
    aliases: [chest, regen, chestregeneration, regeneration, cr]
permissions:
  chestregen.cr:
    default: op
  chestregen.create:
    default: op
  chestregen.use:
    default: true